### ISSUE TITLE
Fehlermeldung  nach Installation durch die EXT:mklib

### ISSUE THREAD

**Issue by chuenniger** [DMKEBUSINESSGMBH/typo3-mkabtesting#1]
Hi,

nach der Installation der Version 1.0.4 aus dem TER schlägt der Aufruf der TYPO3 Seite fehl.

`Fatal error: Class 'tx_rnbase_util_TYPO3' not found in /Users/chuenniger/Documents/mamp/www/mellow/inform/typo3conf/ext/mklib/ext_localconf.php on line 17`

Falls Ihr noch Infos braucht, fragt nach.

Specs:
- TYPO3 6.2.17

**Comment by hannesbochmann** [comment]
Das liegt an einem Bug in der Extension mklib, welcher aber bereits behoben wurde nur leider noch nicht veröffentlicht. Am einfachsten ist das selbst per Hotfix zu beheben. Dazu muss vor Zeile 17 in /Users/chuenniger/Documents/mamp/www/mellow/inform/typo3conf/ext/mklib/ext_localconf.php die folgende Zeile eingefügt werden:
tx_rnbase::load('tx_rnbase_util_TYPO3');

**Comment by chuenniger** [comment]
Alles klar,

vielen Dank für die schnelle Hilfe @hannesbochmann .
